# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

clone:
  enabled: false

pipelines:
  default:
    - step:
        name: 'generate server go code'
        image: golang:1.15
        script:
          - pwd
          - git clone --depth=1 --branch $BITBUCKET_BRANCH https://$BITBUCKET_USERNAME:$BITBUCKET_PASSWORD@bitbucket.org/funplus/proto.git
          - git clone --depth=1 --branch $BITBUCKET_BRANCH https://$BITBUCKET_USERNAME:$BITBUCKET_PASSWORD@bitbucket.org/funplus/server.git
          - git clone --depth=1 --branch $BITBUCKET_BRANCH https://$BITBUCKET_USERNAME:$BITBUCKET_PASSWORD@bitbucket.org/funplus/ee_client.git
          - ls -al
          - cd proto
          - COMMIT_SHORT_HASH=`git rev-parse --short HEAD`
          - COMMIT_MESSAGE=`git log --format=%B -n 1`
          - go get google.golang.org/protobuf/cmd/protoc-gen-go
          - go get github.com/micro/protoc-gen-micro/v2
          - protoc-gen-go --version
          - make linux_proto

          - cd ../server
          - git status
          - git add proto/* || true
          - git config --global user.email "commits-noreply@bitbucket.org"
          - git config --global user.name "bitbucket-pipelines"
          - git commit -am "[proto-pipeline] hash_id:$COMMIT_SHORT_HASH commit_msg:$COMMIT_MESSAGE ..." || true
          - git push origin $BITBUCKET_BRANCH || true

          - cd ../ee_client
          - git status
          - git add proto/*.cs || true
          - git commit -am "[proto-pipeline] hash_id:$COMMIT_SHORT_HASH commit_msg:$COMMIT_MESSAGE ..." || true
          - git push origin $BITBUCKET_BRANCH || true