# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

clone:
  enabled: false

pipelines:
  default:
    - step:
        name: 'generate server go code'
        image: golang:1.15
        script:
          - pwd
          - git clone --depth=1 --branch $BITBUCKET_BRANCH https://$BITBUCKET_USERNAME:$BITBUCKET_PASSWORD@bitbucket.org/funplus/proto.git
          - git clone --depth=1 --branch $BITBUCKET_BRANCH https://$BITBUCKET_USERNAME:$BITBUCKET_PASSWORD@bitbucket.org/funplus/server.git
          - ls -al
          - cd proto
          - cp ./bin/protoc /bin/
          - go get google.golang.org/protobuf/cmd/protoc-gen-go
          - go get github.com/micro/protoc-gen-micro/v2
          - protoc --version
          - protoc-gen-go --version
          - make linux_proto
          - cd ../server
          - git status
          - git config --global user.email "tao.wan@centurygame.com"
          - git config --global user.name "万韬"
          - git commit -am "bitbucket pipeline generate proto source code ..."
          - git push origin $BITBUCKET_BRANCH
